version: "3"
include:
  - docker-dev.yml
services:
  directus:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_DIRECTUS_VERSION=${DOCKER_DIRECTUS_VERSION}
    container_name: ${DOCKER_DIRECTUS_CONTAINER_NAME}
    image: ${DOCKER_DIRECTUS_CUSTOM_IMAGE_NAME}:${DOCKER_DIRECTUS_VERSION}
    ports:
      - "8055:8055"
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ${DOCKER_DIRECTUS_FILES}:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ${DOCKER_DIRECTUS_EXTENSIONS}:/directus/extensions
      - ${DOCKER_DIRECTUS_SNAPSHOTS}:/directus/snapshots
      - ./schema-sync:/directus/schema-sync
      - ./scripts:/directus/scripts
      - ./startup.sh:/directus/startup.sh
    networks:
      - directus
    env_file:
      - .env
    depends_on:
      - cache
      - database
    entrypoint: ["/bin/sh", "/directus/startup.sh"]
# networks:
#   directus:
#     name: ${DOCKER_DIRECTUS_NETWORKNAME}
#     external: ${DOCKER_DIRECTUS_EXTERNAL_NETWORK}
